dist: trusty
language: elixir
elixir: 1.9
otp_release: 22.0
services:
  - docker
env:
  global:
    - MYSQL_SOCKET_DIR=/home/travis/tmp/mysqld
    - MYSQL_UNIX_PORT=/home/travis/tmp/mysqld/mysqld.sock
  matrix:
    - DB=mysql:8.0
    - DB=mysql:5.7
    - DB=mysql:5.6
    - DB=mariadb:10.3
matrix:
  include:
    - elixir: 1.4
      otp_release: 18.3
    - elixir: 1.5
      otp_release: 19.3
    - script:
        - mix compile --warnings-as-errors
        - mix format --check-formatted
before_script:
  - sudo service mysql stop
script:
  - scripts/ci.sh
